// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCe45uiEiMgxq4uxm8bRoktuW4-cMjYcE',
    appId: '1:897442764322:web:084915f359e5a4297d1c7b',
    messagingSenderId: '897442764322',
    projectId: 'vue-http-demo-9e410',
    authDomain: 'vue-http-demo-9e410.firebaseapp.com',
    databaseURL: 'https://vue-http-demo-9e410-default-rtdb.firebaseio.com',
    storageBucket: 'vue-http-demo-9e410.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQq9a84h0A5uEKG4AIhHNWLEtX8fACMj0',
    appId: '1:897442764322:android:d3af7568d3958cb67d1c7b',
    messagingSenderId: '897442764322',
    projectId: 'vue-http-demo-9e410',
    databaseURL: 'https://vue-http-demo-9e410-default-rtdb.firebaseio.com',
    storageBucket: 'vue-http-demo-9e410.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVH5S0kd8MNHXsyx4tp3uj-j3q7v35OPo',
    appId: '1:897442764322:ios:26dd342bff0be6a17d1c7b',
    messagingSenderId: '897442764322',
    projectId: 'vue-http-demo-9e410',
    databaseURL: 'https://vue-http-demo-9e410-default-rtdb.firebaseio.com',
    storageBucket: 'vue-http-demo-9e410.firebasestorage.app',
    androidClientId: '897442764322-8t9jnkb3mc7k806f2qn1oq3njc7bnhcv.apps.googleusercontent.com',
    iosClientId: '897442764322-kp8od5qcbaqou9bnncd28fi0gllh0ntj.apps.googleusercontent.com',
    iosBundleId: 'com.example.acroAttendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVH5S0kd8MNHXsyx4tp3uj-j3q7v35OPo',
    appId: '1:897442764322:ios:26dd342bff0be6a17d1c7b',
    messagingSenderId: '897442764322',
    projectId: 'vue-http-demo-9e410',
    databaseURL: 'https://vue-http-demo-9e410-default-rtdb.firebaseio.com',
    storageBucket: 'vue-http-demo-9e410.firebasestorage.app',
    androidClientId: '897442764322-8t9jnkb3mc7k806f2qn1oq3njc7bnhcv.apps.googleusercontent.com',
    iosClientId: '897442764322-kp8od5qcbaqou9bnncd28fi0gllh0ntj.apps.googleusercontent.com',
    iosBundleId: 'com.example.acroAttendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCe45uiEiMgxq4uxm8bRoktuW4-cMjYcE',
    appId: '1:897442764322:web:6637556ad170ddfa7d1c7b',
    messagingSenderId: '897442764322',
    projectId: 'vue-http-demo-9e410',
    authDomain: 'vue-http-demo-9e410.firebaseapp.com',
    databaseURL: 'https://vue-http-demo-9e410-default-rtdb.firebaseio.com',
    storageBucket: 'vue-http-demo-9e410.firebasestorage.app',
  );
}
